.PHONY: pypi, tag, test

pypi:
	rm -f dist/*
	python setup.py sdist
	twine upload --config-file=.pypirc dist/*
	make tag

tag:
	git tag $$(python -c "from automock.__about__ import __version__; print __version__")
	git push --tags

test:
	AUTOMOCK_APP_CONFIG=tests.settings py.test -v -s --pdb tests/
