version: 2.0

jobs:
  "python-2.7":
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - restore_cache:
          key: py27-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-test.txt" }}
      - run:
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -r requirements-test.txt
      - save_cache:
          key: py27-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-test.txt" }}
          paths:
            - "venv"
      - run:
          environment:
            - AUTOMOCK_APP_CONFIG: tests.settings
          command: |
            . venv/bin/activate
            mkdir -p /tmp/results
            py.test -v -s --junitxml=/tmp/results/pytest.xml tests/
      - store_artifacts:
          path: /tmp/results
          destination: python-2.7

  "python-3.6":
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: py36-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-test.txt" }}
      - run:
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements-test.txt
      - save_cache:
          key: py36-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-test.txt" }}
          paths:
            - "venv"
      - run:
          environment:
            - AUTOMOCK_APP_CONFIG: tests.settings
          command: |
            . venv/bin/activate
            mkdir -p /tmp/results
            mypy --py2 --ignore-missing-imports --junit-xml=/tmp/results/mypy.xml automock
            py.test -v -s --junitxml=/tmp/results/pytest.xml tests/
      - store_artifacts:
          path: /tmp/results
          destination: python-3.6

  "python-3.7":
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
          key: py37-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-test.txt" }}
      - run:
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements-test.txt
      - save_cache:
          key: py37-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-test.txt" }}
          paths:
            - "venv"
      - run:
          environment:
            - AUTOMOCK_APP_CONFIG: tests.settings
          command: |
            . venv/bin/activate
            mkdir -p /tmp/results
            mypy --py2 --ignore-missing-imports --junit-xml=/tmp/results/mypy.xml automock
            py.test -v -s --junitxml=/tmp/results/pytest.xml tests/
      - store_artifacts:
          path: /tmp/results
          destination: python-3.7

  "python-3.8":
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: py38-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-test.txt" }}
      - run:
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements-test.txt
      - save_cache:
          key: py38-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements-test.txt" }}
          paths:
            - "venv"
      - run:
          environment:
            - AUTOMOCK_APP_CONFIG: tests.settings
          command: |
            . venv/bin/activate
            mkdir -p /tmp/results
            mypy --py2 --ignore-missing-imports --junit-xml=/tmp/results/mypy.xml automock
            py.test -v -s --junitxml=/tmp/results/pytest.xml tests/
      - store_artifacts:
          path: /tmp/results
          destination: python-3.8

workflows:
  version: 2
  build:
    jobs:
      - "python-2.7"
      - "python-3.6"
      - "python-3.7"
      - "python-3.8"
